version: "3"

services:
  api:
    build: ./ChatBackend
    image: api
    command: dotnet run
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_HOST: postgres
    ports:
      - "5000:80"
    volumes:
      - ./ChatBackend:/usr/src/backend

  postgres:
    build: ./postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres  # Changing either User, Pass or DB requires updating alembic.ini:53 and chat_app_api.app:10
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: chat_app
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - ~/.chat_app/pgdata:/var/lib/postgres/data/pgdata

  ui:
    build: ./ui
    image: ui
    command: npm run start
    environment:
      PORT: 3000
      CHAT_API_ENDPOINT: http://localhost:5000
      ROOM_API_ENDPOINT: http://localhost:5000/rooms
      AUTH_API_ENDPOINT: http://localhost:5000/auth
      MESSAGE_API_ENDPOINT: http://localhost:5000/messages
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
